### ISSUE TITLE
Specs not being loaded recursively

### ISSUE THREAD

**Issue by TildeWill** [cantino/huginn_agent#4]
Just started a new gem for the Lifx Agents. I'm pretty excited about having lots of agent gems to pick and choose and being able to configure them via ENV variables.

My repo is at omniscopeio/huginn_lifx_agents

The two spec files at the root of `/spec` run just fine, but the specs at `/spec/concerns` and `/spec/clients` don't get picked up. 

It looks like specs are somehow being run through cantino/huginn to pick up the `rails_helper`, but I don't understand how that would interfere with RSpecs --pattern and not look recursively through the spec directories.

**Comment by dsander** [comment]
That is true, can you try if changing [this line](https://github.com/cantino/huginn_agent/blob/master/lib/huginn_agent/spec_runner.rb#L42) to `"bundle exec rspec ../**/*.rb"` solves the problem?

**Comment by TildeWill** [comment]
The pattern you suggested runs the specs in subfolders of `spec` but not at the root level of `spec` :(

**Comment by TildeWill** [comment]
Pull request looks good, thanks for the attention!
