### ISSUE TITLE
How to get code coverage (coveralls?) going?

### ISSUE THREAD

**Issue by stesie** [cantino/huginn_agent#8]
Hey there, I'm not sure if here's the right place to raise this as an issue, but I'm wondering how to get code coverage reporting going with huginn_agent

Maybe some background, I'm not a ruby coder, yet love Huginn and recently wrote a [Todoist Agent](https://github.com/stesie/huginn_todoist_agent) for it. Yet simple, it just allows creating items there (querying still left on todo)

And as Huginn has this hook to report to Coveralls and the agent's specs are run over Huginn it immediately wanted to report to there (but failed with "Couldn't find a repository matching this job." as I didn't register the repo there). So I registered to Coveralls and tried again, ... and reporting is green now.

... yet coverage is wrong, it reports 100% (yay!) but zero files covered (meh). 

This is also reproducible locally:

```console
[stesie@peer 130 ~/Projekte/huginn_todoist_agent master|✔ ]$ export COVERAGE=1
[stesie@peer 0 ~/Projekte/huginn_todoist_agent master|✔ ]$ bundler exec rake spec
Running specs ...
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 5083
..................

Finished in 2.15 seconds (files took 4.65 seconds to load)
18 examples, 0 failures

Randomized with seed 5083

Coverage report generated for RSpec to /home/stesie/Projekte/huginn_todoist_agent/spec/huginn/coverage.
0.0 / 0.0 LOC (100.0%) covered.
[OK]
```

I suppose this is due to specs + subject under test are outside of the actual source tree (i.e. `../../`), but don't know what (best) to do about that

**Comment by stesie** [comment]
I hacked it together locally now, after all there are two steps to do:

1. `SimpleCov.root` must be set correctly (to `../../` directory) and filter must be changed so it filters out everything except `../../lib/`.  For the moment I just hacked that into `spec/hugin/spec/rails_helper.rb` below the SimpleCov/Coveralls startup stuff

```ruby
SimpleCov.root "/home/stesie/Projekte/huginn_todoist_agent"
SimpleCov.start :rails do
  add_filter do |src|
    !(src.filename =~ /^#{SimpleCov.root}\/lib\//)
  end 
end
```

... that way the coverage information is already correct (yay!). And that would be pretty easy to add.

2. However Git information gathered and uploaded to Coveralls is still wrong. This is it collects the commit information + remotes from Huginn and not from my agent plugin. This goes wrong in the *coveralls gem*, in `lib/coveralls/configuration.rb`

The `self.git` function goes like this:

```ruby
    def self.git
      hash = {}

      Dir.chdir(root) do

        hash[:head] = { 
          :id => ENV.fetch("GIT_ID", `git log -1 --pretty=format:'%H'`),
          :author_name => ENV.fetch("GIT_AUTHOR_NAME", `git log -1 --pretty=format:'%aN'`),
          :author_email => ENV.fetch("GIT_AUTHOR_EMAIL", `git log -1 --pretty=format:'%ae'`),
          :committer_name => ENV.fetch("GIT_COMMITTER_NAME", `git log -1 --pretty=format:'%cN'`),
          :committer_email => ENV.fetch("GIT_COMMITTER_EMAIL", `git log -1 --pretty=format:'%ce'`),
          :message => ENV.fetch("GIT_MESSAGE", `git log -1 --pretty=format:'%s'`)
        }
```

... where `root` is

```ruby
    def self.root
      pwd
    end                                                                                                                                                                 

    def self.pwd
      Dir.pwd
    end
```

... which is `.../spec/huginn/` directory.

**Comment by dsander** [comment]
Hi @stesie,

glad to see `huginn_agent` being used! I tried to use simplecov as well but gave up pretty quickly back then. After a bit of research your assumption seems to be correct:
> By default, SimpleCov filters everything outside of the SimpleCov.root directory. However, sometimes you may want to include coverage reports for things you include as a gem, for example a Rails Engine.

Configuring `simplecov` to include the Agent gem code can be done in `spec/huginn/spec/rails_helper.rb`:
```ruby
  SimpleCov.start 'rails' do
    filters.clear
    add_filter do |src|
      !(src.filename =~ /^#{File.expand_path(File.join(SimpleCov.root, '../../lib'))}/)
    end
  end
```

I am now searching for a way to do that automatically without having to search and replace the snippet in Huginn's rails_helper.

**Comment by dsander** [comment]
Ah nice, you beat me to it. 😄  The coveralls problem looks trickier. I wonder if we could run rspec from the Agent gems root directory but still load the Huginn application.

**Comment by stesie** [comment]
hmmm, with Ruby's monkey patching stuff (TBH this still scares me) it could look like this

```diff
diff --git a/spec/rails_helper.rb b/spec/rails_helper.rb
index 8d97bdf..9f2c442 100644
--- a/spec/rails_helper.rb
+++ b/spec/rails_helper.rb
@@ -8,6 +8,23 @@ else
   Coveralls.wear!('rails')
 end
 
+if ENV['HUGINN_EXTERNAL_AGENT_ROOT']
+  SimpleCov.root ENV['HUGINN_EXTERNAL_AGENT_ROOT']
+  SimpleCov.start :rails do
+    add_filter do |src|
+      !(src.filename =~ /^#{SimpleCov.root}\/lib\//)
+    end
+  end
+
+  module Coveralls
+    module Configuration
+      def self.root
+        ENV['HUGINN_EXTERNAL_AGENT_ROOT']
+      end
+    end
+  end
+end
+
 require File.expand_path("../../config/environment", __FILE__)
 require 'rspec/rails'
 require 'rr'
```

... if we'd add that to Huginn and let huginn_agent set the `HUGINN_EXTERNAL_AGENT_ROOT` env variable, everything should work fine :)

Let me know if you like that idea, then I'll follow up with pull requests on huginn and huginn_agent respectively

**Comment by stesie** [comment]
hmm, nope!  Way simpler, Huginn already does require `../../config/environment`  :-)

**Comment by dsander** [comment]
Right, monkey patching probably isn't the prettiest solution, but I doubt the coveralls maintainers would accept a PR to change the root path.

I was able to keep the patch inside `huginn_agent` without the need to modify `Huginn` itself. Does this also work for coveralls?
```patch

diff --git a/lib/huginn_agent/patches/coverage.rb b/lib/huginn_agent/patches/coverage.rb
new file mode 100644
index 0000000..8e85394
--- /dev/null
+++ b/lib/huginn_agent/patches/coverage.rb
@@ -0,0 +1,21 @@
+gem_root = File.expand_path(File.join(Dir.pwd, '../..'))
+
+if ENV['COVERAGE']
+  require 'simplecov'
+
+  SimpleCov.root gem_root
+  SimpleCov.start :rails do
+    add_filter do |src|
+      !(src.filename =~ /^#{SimpleCov.root}\/lib\//)
+    end
+  end
+else
+  require 'coveralls'
+  module Coveralls
+    module Configuration
+      def self.root
+        gem_root
+      end
+    end
+  end
+end
diff --git a/lib/huginn_agent/spec_runner.rb b/lib/huginn_agent/spec_runner.rb
index d567c7a..40ff634 100644
--- a/lib/huginn_agent/spec_runner.rb
+++ b/lib/huginn_agent/spec_runner.rb
@@ -39,7 +39,7 @@ class HuginnAgent

     def spec
       Dir.chdir('spec/huginn') do
-        shell_out "bundle exec rspec --pattern ../*_spec.rb,../{[!huginn/]}**/*_spec.rb", 'Running specs ...', true
+        shell_out "bundle exec rspec -r #{File.join(__dir__, 'patches/coverage.rb')} --pattern ../*_spec.rb,../{[!huginn/]}**/*_spec.rb", 'Running specs ...', true
       end
     end

```

**Comment by stesie** [comment]
very nice!

minor error:

```
Coveralls git error:
undefined local variable or method `gem_root' for Coveralls::Configuration:Module
Coveralls encountered an exception:
NameError
undefined local variable or method `gem_root' for Coveralls::Configuration:Module
/var/lib/gems/2.3.0/gems/huginn_agent-0.4.3/lib/huginn_agent/patches/coverage.rb:17:in `root'
/var/lib/gems/2.3.0/gems/coveralls-0.7.12/lib/coveralls/configuration.rb:108:in `configuration_path'
/var/lib/gems/2.3.0/gems/coveralls-0.7.12/lib/coveralls/configuration.rb:102:in `yaml_config'
/var/lib/gems/2.3.0/gems/coveralls-0.7.12/lib/coveralls/configuration.rb:12:in `configuration'
/var/lib/gems/2.3.0/gems/coveralls-0.7.12/lib/coveralls/api.rb:65:in `apified_hash'
/var/lib/gems/2.3.0/gems/coveralls-0.7.12/lib/coveralls/api.rb:22:in `post_json'
/var/lib/gems/2.3.0/gems/coveralls-0.7.12/lib/coveralls/simplecov.rb:72:in `format'
/var/lib/gems/2.3.0/gems/simplecov-0.9.2/lib/simplecov/result.rb:46:in `format!'
/var/lib/gems/2.3.0/gems/simplecov-0.9.2/lib/simplecov/configuration.rb:158:in `block in at_exit'
/var/lib/gems/2.3.0/gems/simplecov-0.9.2/lib/simplecov/defaults.rb:54:in `block in <top (required)>'
```

... as gem_root isn't available within the modules.

Also SimpleCov root & filter must be defined for coveralls also.  So a working `coverage.rb` (that supports coveralls as well as local coverage generation based on simplecov) looks like that

```ruby
require 'simplecov'                                                                                                                                                     

if !ENV['COVERAGE']
  require 'coveralls'
  module Coveralls
    module Configuration
      def self.root
        File.expand_path(File.join(Dir.pwd, '../..'))
      end 
    end 
  end 
end

SimpleCov.root File.expand_path(File.join(Dir.pwd, '../..'))
SimpleCov.start :rails do
  add_filter do |src|
    !(src.filename =~ /^#{SimpleCov.root}\/lib\//)
  end 
end
```

... so at least running it locally it looks fine: https://coveralls.io/builds/9970584
Cannot test w/ travis until a updated Gem is available :)

**Comment by dsander** [comment]
Ah, missed that. I guess we could enable `simplecov` by default, if not we would need to find a way to configure simplecov for coveralls but not start if when `COVERAGE` is not set. 

Would you mind opening a PR with the changes? 

I think you can test it on travis by adding the `huginn_agent` gem to your `Gemfile` which overrides the version specified in the `gemspec`:

```ruby
gemspec
gem 'huginn_agent', github: 'stesie/huginn_agent', branch: 'somebranch'
```
